id: 2c5b00568b6042d38b57a9277e4c2170
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_103-The_Teaching_by_the_Child_Inconceivable_Radiance-v2
  language: bo
  author: ''
  volume: {}
